import { cn } from "@/lib/utils";

type Tone = "neutral" | "success" | "warning" | "danger" | "info" | "primary";

const TONE_CLASS: Record<Tone, string> = {
  neutral: "border-border bg-muted text-muted-foreground",
  success: "border-success/40 bg-success/12 text-success",
  warning: "border-warning/40 bg-warning/12 text-warning",
  danger: "border-destructive/45 bg-destructive/12 text-destructive",
  info: "border-info/40 bg-info/12 text-info",
  primary: "border-primary/45 bg-primary/12 text-primary",
};

export function StatusChip({
  label,
  tone = "neutral",
  className,
  dot = true,
}: {
  label: string;
  tone?: Tone;
  className?: string;
  dot?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-sm border px-2 py-0.5 font-display text-[10px] font-semibold uppercase tracking-[0.09em]",
        TONE_CLASS[tone],
        className,
      )}
    >
      {dot ? <span className="size-1.5 rounded-full bg-current" /> : null}
      {label}
    </span>
  );
}

export function toneForDroneStatus(status: string): Tone {
  switch (status) {
    case "available":
      return "success";
    case "flying":
      return "primary";
    case "assigned":
      return "info";
    case "charging":
      return "warning";
    case "maintenance":
      return "warning";
    default:
      return "neutral";
  }
}

export function toneForFlightStatus(status: string): Tone {
  switch (status) {
    case "completed":
      return "success";
    case "in_progress":
      return "primary";
    case "preflight":
    case "assigned":
      return "info";
    case "aborted":
    case "failed":
      return "danger";
    default:
      return "neutral";
  }
}

export function toneForResult(result: string | null): Tone {
  switch (result) {
    case "completed":
      return "success";
    case "partial":
      return "warning";
    case "aborted":
    case "failed":
      return "danger";
    default:
      return "neutral";
  }
}

export function toneForReadiness(state: string): Tone {
  if (state === "READY") return "success";
  if (state === "BLOCKED") return "danger";
  return "warning";
}

export function toneForDevice(status: string): Tone {
  if (status === "active") return "success";
  if (status === "revoked") return "danger";
  if (status === "update_required") return "warning";
  return "neutral";
}

export function toneForIntegration(status: string): Tone {
  if (status === "connected") return "success";
  if (status === "error") return "danger";
  if (status === "flight_agent_required") return "warning";
  if (status === "coming_soon") return "info";
  return "neutral";
}

export function DemoBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-sm border border-info/40 bg-info/10 px-1.5 py-0.5 font-display text-[9px] font-semibold uppercase tracking-[0.12em] text-info",
        className,
      )}
    >
      Demo data
    </span>
  );
}

export function SimulationBanner({ text = "SIMULATION MODE — telemetry below is generated by this platform and is not DJI aircraft data" }) {
  return (
    <div className="flex items-center gap-2 border-y border-warning/40 bg-warning/12 px-4 py-2 font-display text-[11px] font-semibold uppercase tracking-[0.12em] text-warning">
      <span className="size-2 animate-pulse rounded-full bg-warning" />
      {text}
    </div>
  );
}

export function NotConfiguredNotice({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-md border border-dashed border-border bg-panel/60 p-4">
      <p className="font-display text-[11px] font-semibold uppercase tracking-[0.12em] text-warning">{title}</p>
      <p className="mt-1 text-sm text-muted-foreground">{body}</p>
    </div>
  );
}
