/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedFlightsIndexRouteImport } from './routes/_authenticated/flights.index'
import { Route as AuthenticatedFlightsFlightIdRouteImport } from './routes/_authenticated/flights.$flightId'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions.$missionId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedSimulateMissionIdRouteImport } from './routes/_authenticated/simulate.$missionId'
import { Route as ApiPublicAgentEventsRouteImport } from './routes/api/public/agent/events'
import { Route as ApiPublicAgentFlightsRouteImport } from './routes/api/public/agent/flights'
import { Route as ApiPublicAgentMediaRouteImport } from './routes/api/public/agent/media'
import { Route as ApiPublicAgentMissionsRouteImport } from './routes/api/public/agent/missions'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentTelemetryRouteImport } from './routes/api/public/agent/telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlightsIndexRoute =
  AuthenticatedFlightsIndexRouteImport.update({
    id: '/flights/',
    path: '/flights/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlightsFlightIdRoute =
  AuthenticatedFlightsFlightIdRouteImport.update({
    id: '/flights/$flightId',
    path: '/flights/$flightId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulateMissionIdRoute =
  AuthenticatedSimulateMissionIdRouteImport.update({
    id: '/simulate/$missionId',
    path: '/simulate/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentEventsRoute = ApiPublicAgentEventsRouteImport.update({
  id: '/api/public/agent/events',
  path: '/api/public/agent/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentFlightsRoute = ApiPublicAgentFlightsRouteImport.update({
  id: '/api/public/agent/flights',
  path: '/api/public/agent/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentMediaRoute = ApiPublicAgentMediaRouteImport.update({
  id: '/api/public/agent/media',
  path: '/api/public/agent/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentMissionsRoute = ApiPublicAgentMissionsRouteImport.update({
  id: '/api/public/agent/missions',
  path: '/api/public/agent/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTelemetryRoute = ApiPublicAgentTelemetryRouteImport.update({
  id: '/api/public/agent/telemetry',
  path: '/api/public/agent/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/simulate/$missionId': typeof AuthenticatedSimulateMissionIdRoute
  '/flights/': typeof AuthenticatedFlightsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/flights': typeof ApiPublicAgentFlightsRoute
  '/api/public/agent/media': typeof ApiPublicAgentMediaRoute
  '/api/public/agent/missions': typeof ApiPublicAgentMissionsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/telemetry': typeof ApiPublicAgentTelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/simulate/$missionId': typeof AuthenticatedSimulateMissionIdRoute
  '/flights': typeof AuthenticatedFlightsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/flights': typeof ApiPublicAgentFlightsRoute
  '/api/public/agent/media': typeof ApiPublicAgentMediaRoute
  '/api/public/agent/missions': typeof ApiPublicAgentMissionsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/telemetry': typeof ApiPublicAgentTelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/simulate/$missionId': typeof AuthenticatedSimulateMissionIdRoute
  '/_authenticated/flights/': typeof AuthenticatedFlightsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/flights': typeof ApiPublicAgentFlightsRoute
  '/api/public/agent/media': typeof ApiPublicAgentMediaRoute
  '/api/public/agent/missions': typeof ApiPublicAgentMissionsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/telemetry': typeof ApiPublicAgentTelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fleet'
    | '/integrations'
    | '/media'
    | '/reports'
    | '/flights/$flightId'
    | '/missions/$missionId'
    | '/projects/$projectId'
    | '/simulate/$missionId'
    | '/flights/'
    | '/projects/'
    | '/api/public/agent/events'
    | '/api/public/agent/flights'
    | '/api/public/agent/media'
    | '/api/public/agent/missions'
    | '/api/public/agent/register'
    | '/api/public/agent/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fleet'
    | '/integrations'
    | '/media'
    | '/reports'
    | '/flights/$flightId'
    | '/missions/$missionId'
    | '/projects/$projectId'
    | '/simulate/$missionId'
    | '/flights'
    | '/projects'
    | '/api/public/agent/events'
    | '/api/public/agent/flights'
    | '/api/public/agent/media'
    | '/api/public/agent/missions'
    | '/api/public/agent/register'
    | '/api/public/agent/telemetry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/fleet'
    | '/_authenticated/integrations'
    | '/_authenticated/media'
    | '/_authenticated/reports'
    | '/_authenticated/flights/$flightId'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/simulate/$missionId'
    | '/_authenticated/flights/'
    | '/_authenticated/projects/'
    | '/api/public/agent/events'
    | '/api/public/agent/flights'
    | '/api/public/agent/media'
    | '/api/public/agent/missions'
    | '/api/public/agent/register'
    | '/api/public/agent/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentEventsRoute: typeof ApiPublicAgentEventsRoute
  ApiPublicAgentFlightsRoute: typeof ApiPublicAgentFlightsRoute
  ApiPublicAgentMediaRoute: typeof ApiPublicAgentMediaRoute
  ApiPublicAgentMissionsRoute: typeof ApiPublicAgentMissionsRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentTelemetryRoute: typeof ApiPublicAgentTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flights/': {
      id: '/_authenticated/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof AuthenticatedFlightsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flights/$flightId': {
      id: '/_authenticated/flights/$flightId'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof AuthenticatedFlightsFlightIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulate/$missionId': {
      id: '/_authenticated/simulate/$missionId'
      path: '/simulate/$missionId'
      fullPath: '/simulate/$missionId'
      preLoaderRoute: typeof AuthenticatedSimulateMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/events': {
      id: '/api/public/agent/events'
      path: '/api/public/agent/events'
      fullPath: '/api/public/agent/events'
      preLoaderRoute: typeof ApiPublicAgentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/flights': {
      id: '/api/public/agent/flights'
      path: '/api/public/agent/flights'
      fullPath: '/api/public/agent/flights'
      preLoaderRoute: typeof ApiPublicAgentFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/media': {
      id: '/api/public/agent/media'
      path: '/api/public/agent/media'
      fullPath: '/api/public/agent/media'
      preLoaderRoute: typeof ApiPublicAgentMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/missions': {
      id: '/api/public/agent/missions'
      path: '/api/public/agent/missions'
      fullPath: '/api/public/agent/missions'
      preLoaderRoute: typeof ApiPublicAgentMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/telemetry': {
      id: '/api/public/agent/telemetry'
      path: '/api/public/agent/telemetry'
      fullPath: '/api/public/agent/telemetry'
      preLoaderRoute: typeof ApiPublicAgentTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedFlightsFlightIdRoute: typeof AuthenticatedFlightsFlightIdRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedSimulateMissionIdRoute: typeof AuthenticatedSimulateMissionIdRoute
  AuthenticatedFlightsIndexRoute: typeof AuthenticatedFlightsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedFlightsFlightIdRoute: AuthenticatedFlightsFlightIdRoute,
  AuthenticatedMissionsMissionIdRoute: AuthenticatedMissionsMissionIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedSimulateMissionIdRoute: AuthenticatedSimulateMissionIdRoute,
  AuthenticatedFlightsIndexRoute: AuthenticatedFlightsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentEventsRoute: ApiPublicAgentEventsRoute,
  ApiPublicAgentFlightsRoute: ApiPublicAgentFlightsRoute,
  ApiPublicAgentMediaRoute: ApiPublicAgentMediaRoute,
  ApiPublicAgentMissionsRoute: ApiPublicAgentMissionsRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentTelemetryRoute: ApiPublicAgentTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
